#include "compiler/backend_m68k/backend.h"

#include <stdarg.h>
#include <stdio.h>
#include <string.h>

#include "compiler/abi/abi.h"

static int output_line(FILE *output, const char *format, ...)
{
    int written;
    va_list arguments;

    va_start(arguments, format);
    written = vfprintf(output, format, arguments);
    va_end(arguments);
    return written >= 0;
}

static int output_failure(struct miga80_diagnostic *diagnostic,
                          const struct miga80_ir_instruction *instruction)
{
    diagnostic->line = instruction == NULL ? 0U : instruction->line;
    diagnostic->column = instruction == NULL ? 0U : instruction->column;
    (void)snprintf(diagnostic->message, sizeof(diagnostic->message),
                   "unable to write GNU m68k assembly");
    return 0;
}

int miga80_emit_gnu_m68k(FILE *output,
                         const struct miga80_ir_function *function,
                         struct miga80_diagnostic *diagnostic)
{
    unsigned int index;
    unsigned int frame_size;

    if (output == NULL || function == NULL || diagnostic == NULL) {
        return 0;
    }
    (void)memset(diagnostic, 0, sizeof(*diagnostic));
    if (!miga80_validate_ir(function, diagnostic)) {
        return 0;
    }
    if (function->parameter_count > MIGA80_MAX_PARAMETERS) {
        diagnostic->line = 0U;
        diagnostic->column = 0U;
        (void)snprintf(diagnostic->message, sizeof(diagnostic->message),
                       "function exceeds the initial register ABI");
        return 0;
    }
    frame_size = (function->parameter_count + function->local_count) * 4U;
    if (!miga80_abi_frame_size_is_valid(frame_size)) {
        (void)snprintf(diagnostic->message, sizeof(diagnostic->message),
                       "function frame violates native ABI 0.1");
        return 0;
    }

    if (!output_line(output,
                     "/* Generated by miga80c -O0 for native ABI %u.%u; "
                     "development oracle only. */\n"
                     "        .text\n"
                     "        .even\n"
                     "        .globl  %s\n"
                     "%s:\n"
                     "        link.w  %%a6,#-%u\n",
                     MIGA80_ABI_VERSION_MAJOR, MIGA80_ABI_VERSION_MINOR,
                     function->name, function->name, frame_size)) {
        return output_failure(diagnostic, NULL);
    }
    for (index = 0; index < function->parameter_count; ++index) {
        enum miga80_abi_register argument_register;
        const char *argument_name;

        if (!miga80_abi_scalar_argument_register(index, &argument_register) ||
            (argument_name =
                 miga80_abi_gnu_register_name(argument_register)) == NULL) {
            diagnostic->line = 0U;
            diagnostic->column = 0U;
            (void)snprintf(diagnostic->message, sizeof(diagnostic->message),
                           "unable to map argument through native ABI 0.1");
            return 0;
        }
        if (!output_line(output, "        move.l  %s,-%u(%%a6)\n",
                         argument_name, (index + 1U) * 4U)) {
            return output_failure(diagnostic, NULL);
        }
    }

    for (index = 0; index < function->instruction_count; ++index) {
        const struct miga80_ir_instruction *instruction =
            &function->instructions[index];
        unsigned int block_index;
        int success = 1;

        for (block_index = 0U; block_index < function->block_count;
             ++block_index) {
            if (function->blocks[block_index].first_instruction == index &&
                !output_line(output, ".L_%s_b%u:\n", function->name,
                             block_index)) {
                return output_failure(diagnostic, instruction);
            }
        }

        switch (instruction->opcode) {
        case MIGA80_IR_PUSH_I32:
        case MIGA80_IR_PUSH_BOOL:
            success = output_line(output,
                                  "        move.l  #0x%08x,-(%%a7)\n",
                                  (unsigned int)instruction->operand);
            break;
        case MIGA80_IR_PUSH_PARAMETER_I32:
        case MIGA80_IR_PUSH_PARAMETER_BOOL:
            if (instruction->operand >= function->parameter_count) {
                diagnostic->line = instruction->line;
                diagnostic->column = instruction->column;
                (void)snprintf(diagnostic->message,
                               sizeof(diagnostic->message),
                               "typed IR parameter index exceeds ABI");
                return 0;
            }
            success = output_line(output, "        move.l  -%u(%%a6),-(%%a7)\n",
                                  (instruction->operand + 1U) * 4U);
            break;
        case MIGA80_IR_PUSH_LOCAL_I32:
        case MIGA80_IR_PUSH_LOCAL_BOOL:
            if (instruction->operand >= function->local_count) {
                diagnostic->line = instruction->line;
                diagnostic->column = instruction->column;
                (void)snprintf(diagnostic->message,
                               sizeof(diagnostic->message),
                               "typed IR local index exceeds frame");
                return 0;
            }
            success = output_line(
                output, "        move.l  -%u(%%a6),-(%%a7)\n",
                (function->parameter_count + instruction->operand + 1U) *
                    4U);
            break;
        case MIGA80_IR_STORE_LOCAL_I32:
        case MIGA80_IR_STORE_LOCAL_BOOL:
            if (instruction->operand >= function->local_count) {
                diagnostic->line = instruction->line;
                diagnostic->column = instruction->column;
                (void)snprintf(diagnostic->message,
                               sizeof(diagnostic->message),
                               "typed IR local store exceeds frame");
                return 0;
            }
            success = output_line(
                output,
                "        move.l  (%%a7)+,%%d0\n"
                "        move.l  %%d0,-%u(%%a6)\n",
                (function->parameter_count + instruction->operand + 1U) *
                    4U);
            break;
        case MIGA80_IR_NEG_I32:
            success = output_line(output,
                                  "        move.l  (%%a7)+,%%d0\n"
                                  "        neg.l   %%d0\n"
                                  "        move.l  %%d0,-(%%a7)\n");
            break;
        case MIGA80_IR_ADD_I32:
        case MIGA80_IR_SUB_I32:
        case MIGA80_IR_MUL_I32:
        case MIGA80_IR_EQ_I32:
        case MIGA80_IR_NE_I32:
        case MIGA80_IR_EQ_BOOL:
        case MIGA80_IR_NE_BOOL:
        case MIGA80_IR_LT_I32:
        case MIGA80_IR_LE_I32:
        case MIGA80_IR_GT_I32:
        case MIGA80_IR_GE_I32:
            success = output_line(output,
                                  "        move.l  (%%a7)+,%%d1\n"
                                  "        move.l  (%%a7)+,%%d0\n");
            if (success && instruction->opcode == MIGA80_IR_ADD_I32) {
                success = output_line(output, "        add.l   %%d1,%%d0\n");
            } else if (success &&
                       instruction->opcode == MIGA80_IR_SUB_I32) {
                success = output_line(output, "        sub.l   %%d1,%%d0\n");
            } else if (success &&
                       instruction->opcode == MIGA80_IR_MUL_I32) {
                success = output_line(output, "        muls.l  %%d1,%%d0\n");
            } else if (success) {
                const char *condition = "seq";

                if (instruction->opcode == MIGA80_IR_NE_I32 ||
                    instruction->opcode == MIGA80_IR_NE_BOOL) {
                    condition = "sne";
                } else if (instruction->opcode == MIGA80_IR_LT_I32) {
                    condition = "slt";
                } else if (instruction->opcode == MIGA80_IR_LE_I32) {
                    condition = "sle";
                } else if (instruction->opcode == MIGA80_IR_GT_I32) {
                    condition = "sgt";
                } else if (instruction->opcode == MIGA80_IR_GE_I32) {
                    condition = "sge";
                }
                success = output_line(output,
                                      "        cmp.l   %%d1,%%d0\n"
                                      "        %s     %%d0\n"
                                      "        and.l   #1,%%d0\n",
                                      condition);
            }
            if (success) {
                success =
                    output_line(output, "        move.l  %%d0,-(%%a7)\n");
            }
            break;
        case MIGA80_IR_BRANCH_FALSE:
            success = output_line(output,
                                  "        move.l  (%%a7)+,%%d0\n"
                                  "        tst.l   %%d0\n"
                                  "        beq     .L_%s_b%u\n",
                                  function->name,
                                  (unsigned int)instruction->operand);
            break;
        case MIGA80_IR_JUMP:
            success = output_line(output, "        bra     .L_%s_b%u\n",
                                  function->name,
                                  (unsigned int)instruction->operand);
            break;
        case MIGA80_IR_RETURN:
            success = output_line(output,
                                  "        move.l  (%%a7)+,%%d0\n"
                                  "        unlk    %%a6\n"
                                  "        rts\n");
            break;
        default:
            diagnostic->line = instruction->line;
            diagnostic->column = instruction->column;
            (void)snprintf(diagnostic->message, sizeof(diagnostic->message),
                           "unknown typed IR instruction in m68k backend");
            return 0;
        }
        if (!success) {
            return output_failure(diagnostic, instruction);
        }
    }

    if (fflush(output) != 0 || ferror(output)) {
        return output_failure(diagnostic, NULL);
    }
    return 1;
}
